AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.lambda_handler
      ReservedConcurrentExecutions: 3
      Runtime: python3.8
      Events:
        GetHello:
          Type: Api 
          Properties:
            RestApiId: 
              Ref: HelloWorldApi
            Path: /hello
            Method: get

  HelloWorldLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: HelloWorldApiLogGroup
      RetentionInDays: 7

  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties: 
      Name: HelloWorldApi
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM
      AccessLogSetting:
        DestinationArn: !GetAtt HelloWorldLogGroup.Arn
        Format: '$context.identity.sourceIp $context.requestTime $context.httpMethod $context.resourcePath $context.protocol $context.status $context.responseLength $context.requestId'

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com"
