[package]
name = "hello_world" 
version = "0.1.0"   

[dependencies]
chrono = "0.4"
hmac = "0.12"
sha2 = "0.10"
reqwest = { version = "0.11", features = ["blocking"] }
hex = "0.4"

[[bin]]
name = "awssigner"    
path = "./main.rs" 